# -*- coding: utf-8 -*-

CHART_UNITS = 300

""" BAR TYPE """
BAR_TYPE_TIME = 10
BAR_TYPE_TICK = 11
BAR_TYPE_VOLUME = 12
BAR_TYPE_DOLLAR = 13
BAR_TYPE_RANGE = 14
BAR_TYPE_TIB = 21
BAR_TYPE_VIB = 22
BAR_TYPE_DIB = 23
BAR_TYPE_TRB = 31
BAR_TYPE_VRB = 32
BAR_TYPE_DRB = 33

""" Window Size """
LONG_WINDOW_SIZE = 30
MID_WINDOW_SIZE = 10
SHORT_WINDOW_SIZE = 5

CSUM_THRESHOLD = 1.0

""" Position """
BUY_POSITION = 1
SELL_POSITION = -1

""" profit """
LOSS_CUT = -0.2
TRAIL_STOP = 0.3

LOOP_INTERVAL = 1

UPBIT_API_KEY = "pVMqyrk10OqmuxTAcKsRedZsJ3atpFGfQ5XxLsR2"
UPBIT_SECRET = "nxujAKed4Hn1TOTz3TExx7VWao1g52aoOIqKDq48"

BITMEX_API_KEY = "HRtE2PkJA3IXZ8SFLurg6O3Y"
BITMEX_SECRET = "41N1C6_H-Qm2_3W3Q0zc0KLIdorG6gOYN6HsN73o_3wYIYqb"

BTC_KRW_TICKER = "BTC/KRW"
BTC_USD_TICKER = "BTC/USD"

BAR_INTERVAL = "5m"

"""TRADER"""
LONG_EXCHANGE = 'upbit'
SHORT_EXCHANGE = 'bitmex'
LONG_EXCHANGE_TAKER_FEE = 0.0005
SHORT_EXCHANGE_MAKER_FEE = -0.0002

BENCHMARK = 'USD/KRW'
ENTRY_PREMIUM_VALUE = 10.
EXIT_PREMIUM_VALUE = 0.

K_ENTRY_POINT = -2.0
K_EXIT_POINT = 1.0
